CREATE USER IF NOT EXISTS 'g8'@'%' IDENTIFIED BY 'hk49-Sk94K23m';
GRANT ALL PRIVILEGES ON *.* TO 'g8'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

-- Ensure target app database exists
CREATE DATABASE IF NOT EXISTS rntPy1;
-- Optional sample DB
CREATE DATABASE IF NOT EXISTS demo;
